name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

  security-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start Application for Security Scanning
        run: |
          docker build -t lacrei-saude-app .
          docker run -d -p 8080:3000 lacrei-saude-app

      - name: Zed Attack Proxy
        uses: docker pull zaproxy/zap-stable
        with:
          target: http://localhost:8080
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Vulnerability Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ./zap.out

  deploy:
    runs-on: ubuntu-latest
    needs: security-analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t lacrei-saude-app .
          docker tag lacrei-saude-app:latest ${{ secrets.DOCKER_USERNAME }}/lacrei-saude-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lacrei-saude-app:latest
