name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

  security-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create ZAP Config File
        run: |
          echo "WARN-NEW 10055 WARN" > zap-config.conf
          echo "WARN-NEW 10063 WARN" >> zap-config.conf

      - name: Start Application for Security Scanning
        run: |
          docker build -t lacrei-saude-app .
          docker run -d --name lacrei-saude-app -p 8080:3000 lacrei-saude-app

      - name: Wait for Application to Start
        run: sleep 30

      - name: Run Zed Attack Proxy
        run: |
          docker pull zaproxy/zap-stable
          docker run --network="host" \
            -v "$(pwd)/zap-config.conf:/zap/wrk/zap-config.conf" \
            zaproxy/zap-stable zap-full-scan.py \
            -t http://localhost:8080 \
            -c /zap/wrk/zap-config.conf \
            -r zap-report.html \
            -x zap-report.xml \
            -m 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Vulnerability Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html

      - name: Stop Application Container
        run: docker stop lacrei-saude-app && docker rm lacrei-saude-app

  deploy:
    runs-on: ubuntu-latest
    needs: security-analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t lacrei-saude-app .
          docker tag lacrei-saude-app:latest ${{ secrets.DOCKER_USERNAME }}/lacrei-saude-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lacrei-saude-app:latest
